server/app/urls.py
from des import urls as des_urls
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', admin.site.urls),
    url(r'^django-des/', include(des_urls)),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('robots.txt', include('robots.urls')),

    # url(r'', include('apps.frontend.urls')),
]

api_urlpatterns = [
    re_path(r'api/v(?P<version>[1|2]+)/', include([
        path('', include('apps.novaposhta.urls')),
        path('', include(('apps.accounts.api.urls'))),
    ])),
    # url(r'^rest-auth/', include('rest_auth.urls'))

]
urlpatterns += api_urlpatterns

schema_view = get_schema_view(
    openapi.Info(
        title="API",
        default_version='v1',
        description="Test description",
    ),
    public=False,
    permission_classes=(permissions.AllowAny,),
    patterns=api_urlpatterns
)
urlpatterns += [
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),
         name='schema-swagger-ui'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0),
         name='schema-swagger-ui'),
]
urlpatterns += i18n_patterns(
    path('', include('apps.addition_page.urls')),
    path('', include('apps.core.urls', '')),
    path('accounts/social/',
         include(('apps.social_accounts.urls', 'social_account'))),
    path('accounts/', include(('apps.accounts.urls', 'account'))),
    path('', include(('apps.store.urls', 'store'))),
    path('accounts/', include('allauth.urls')),

    prefix_default_language=False
)

handler404 = 'apps.core.views.page_404'
handler403 = 'apps.core.views.page_403'
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^rosetta/', include('rosetta.urls'))]

if settings.DEBUG:
    urlpatterns += [url(r'^', include('markup.urls'))]
    urlpatterns += (
            static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
            static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

server/apps/store/urls.py
from django.urls import path, include

from .views import (
    ProductListView, ProductDetailView, AddProductInBasketView, BasketView,
    OrderingView, load_warehouse, load_cities, OrderResult, OrderSuccess,
    PayView, PayCallbackView, OrderPaid, MainStorePageView
)

urlpatterns = [
    path('store/', include(([
        path('', MainStorePageView.as_view(), name='main'),
        path('basket/add/<int:pk>/', AddProductInBasketView.as_view(),
             name='add_basket'),
        path('basket/', BasketView.as_view(),
             name='basket'),
        path('ordering/', OrderingView.as_view(),
             name='ordering'),
        path('ordering/result/<str:number_order>/', OrderResult.as_view(),
             name='ordering-result'),
        path('ordering/success', OrderSuccess.as_view(),
             name='ordering-success'),
        path('ordering/paid', OrderPaid.as_view(),
             name='ordering-paid'),
        path('pay/<order>/', PayView.as_view(), name='pay-view'),
        path('pay-callback/', PayCallbackView.as_view(), name='pay-callback'),

        path('ajax/load-warehouses/', load_warehouse,
             name='ajax_load_warehouses'),
        path('ajax/load-cities/', load_cities, name='ajax_load_cities'),
        path('<slug:category>/', ProductListView.as_view(),
             name='main_category'),
        path('<slug:category>/<slug:sub_category>/',
             ProductListView.as_view(),
             name='sub_category'),
        path('<slug:category>/<slug:sub_category>/<slug:slug>/',
             ProductDetailView.as_view(), name='product'),
    ])))
]

server/markup/urls.py
from django.urls import include, re_path

from . import views

urlpatterns = [
    re_path('^', include(([
        *views.PageTemplate.as_urls(),
    ], 'markup')))
]

server/apps/store/models/ordering.py
from constance import config
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _
from ok_images.fields import OptimizedImageField
from versatileimagefield.fields import PPOIField

from shared.models.active import ActiveMixin


class MethodDelivery(ActiveMixin, models.Model):
    title = models.CharField(max_length=255, verbose_name=_('Название'),
                             blank=True)
    description = models.CharField(max_length=255, verbose_name=_('Описание'),
                                   blank=True)

    image = OptimizedImageField(
        _('Image'),
        ppoi_field='ppoi',
        upload_to='delivery/%d%m%y',
        image_sizes='product',
        blank=True,
    )
    ppoi = PPOIField(
        verbose_name=_('Картинка')
    )
    alt = models.CharField(blank=True, max_length=255)
    price_delivery = models.DecimalField(max_digits=10, decimal_places=2,
                                         verbose_name=_('Стоимость доставки'))

    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['order', ]
        verbose_name = _('Способ доставки')
        verbose_name_plural = _('Способы доставки')

    def __str__(self):
        return self.title


class MethodPayment(ActiveMixin, models.Model):
    STATUS = [
        (_('Оплата картой'), (
            ('LiqPAY', 'LiqPAY'),
        )),
        (_('Оффлайн'), (
            ('C.O.D.', _('Наложным платежом')),
            ('cash', _('Наличными')),
        )),
    ]
    title = models.CharField(max_length=255, verbose_name=_('Название'),
                             blank=True)
    description = models.CharField(max_length=255, verbose_name=_('Описание'),
                                   blank=True)
    image = OptimizedImageField(
        _('Image'),
        ppoi_field='ppoi',
        upload_to='products/%d%m%y',
        image_sizes='product',
        blank=True,
        default=config.DEFAULT_IMAGE_404
    )
    ppoi = PPOIField(
        verbose_name=_('Картинка')
    )
    alt = models.CharField(blank=True, max_length=255)

    status = models.CharField(choices=STATUS, max_length=20,
                              default='new',
                              verbose_name=_('Статус'))

    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['order', ]
        verbose_name = _('Способ оплаты')
        verbose_name_plural = _('Способы оплаты')

    def __str__(self):
        return self.title


class Order(models.Model):
    STATUS = (
        ('new', 'New'),
        ('confirmed', 'Confirmed'),
        ('sent', 'Sent'),
        ('done', 'Done'),
        ('canceled', 'Canceled'))

    STATUS_PAYMENT = (
        ('paid', 'Paid'),
        ('not paid', 'Not paid'))
    number_order = models.CharField(max_length=254, unique=True,
                                    verbose_name=_('Код заказа'))
    status = models.CharField(choices=STATUS, max_length=20,
                              default=STATUS[0][0], blank=True,
                              verbose_name=_('Статус'))
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             null=True, blank=True,
                             related_name='order',
                             related_query_name='order',
                             verbose_name=_('Пользователь'))

    basket = models.ForeignKey('Basket', on_delete=models.CASCADE,
                                  related_name='order', blank=True,
                                  related_query_name='order',
                                  verbose_name=_('Корзина'))

    delivery = models.ForeignKey(MethodDelivery, blank=True, null=True,
                                 related_name='orders',
                                 related_query_name='orders',
                                 on_delete=models.CASCADE,
                                 verbose_name=_('Способ доставки')
                                 )
    payment_method = models.ForeignKey(MethodPayment, blank=True, null=True,
                                       related_name='orders',
                                       related_query_name='orders',
                                       on_delete=models.CASCADE,
                                       verbose_name=_('Способ оплаты')
                                       )
    payment_status = models.CharField(choices=STATUS_PAYMENT, max_length=20,
                                      default='not paid',
                                      verbose_name=_('Статус оплаты'))

    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name=_('Создано'))
    updated_at = models.DateTimeField(auto_now=True,
                                      verbose_name=_('Обновлено'))

    class Meta(object):
        ordering = ['-updated_at', ]
        verbose_name = _('Заказ')
        verbose_name_plural = _('Заказы')


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE,
                              related_name='variant_order',
                              related_query_name='variant_order',
                              verbose_name=_('Заказ'))
    product_variant = models.ForeignKey('ProductVariant',
                                        related_name='variant_order',
                                        related_query_name='variant_order',
                                        on_delete=models.CASCADE,
                                        verbose_name=_('Продукт'))
    price_product = models.DecimalField(max_digits=10, decimal_places=2,
                                        default=0,
                                        verbose_name=_('Стоимость продукта'))
    count = models.PositiveSmallIntegerField(default=1,
                                             verbose_name=_('Количество'))
    price_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      default=0,
                                      verbose_name=_('Общая стоимость'))

    class Meta:
        ordering = ['-order', ]
        verbose_name = _('Продукт заказа')
        verbose_name_plural = _('Продукты заказа')
        unique_together = ['order', 'product_variant', ]

    def __str__(self):
        return '{}({})'.format(self.product_variant.vendor_code, self.count)


class Pay(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE,
                                 related_name='pay',
                                 related_query_name='pay',
                                 verbose_name=_('Заказ'))
    price_products = models.DecimalField(max_digits=10, decimal_places=2,
                                         blank=True, default=0,
                                         verbose_name=_('Стоимость продуктов'))
    price_delivery = models.DecimalField(max_digits=10, decimal_places=2,
                                         blank=True, default=0,
                                         verbose_name=_('Стоимость доставки'))
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True,
                                default=0,
                                verbose_name=_('Общая стоимость'))

    class Meta:
        ordering = ['-price', ]
        verbose_name = _('Оплата')
        verbose_name_plural = _('Оплата')


class AddressDelivery(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE,
                                 related_name='address',
                                 related_query_name='address',
                                 verbose_name=_('Заказ'))
    phone = models.CharField(max_length=15, blank=True,
                             verbose_name=_("Телефон"),
                             validators=
                             [RegexValidator(
                                 r"[+]?\d{9,15}",
                                 message=_(
                                     'Не соответствует формату телефона'))])
    first_name = models.CharField(max_length=254,
                                  verbose_name=_('Имя'))
    last_name = models.CharField(max_length=254,
                                 verbose_name=_('Фамилия'))
    email = models.EmailField(max_length=254,
                              verbose_name='Email')

    country = models.CharField(max_length=254, blank=True,
                               verbose_name=_('Страна'))
    index = models.CharField(max_length=10, blank=True,
                             validators=
                             [RegexValidator(
                                 r"^\d{5,10}$",
                                 message=_(
                                     'Не соответствует формату индекса'))],
                             verbose_name=_('Индекс'))
    city = models.CharField(max_length=254, blank=True,
                            verbose_name=_('Город'))
    street = models.CharField(max_length=254, blank=True,
                              verbose_name=_('Улица'))
    number_house = models.CharField(max_length=10, blank=True,
                                    verbose_name=_('Номер дома'))
    number_apartment = models.CharField(max_length=10, blank=True,
                                        verbose_name=_('Номер квартиры'))

    class Meta(object):
        verbose_name = _('Адрес доставки')
        verbose_name_plural = _('Адреса доставки')


class Payment(models.Model):
    STATUS_PAYMENT = (
        ('paid', 'Paid'),
        ('not paid', 'Not paid')
    )
    order = models.OneToOneField(Order, on_delete=models.CASCADE,
                                 related_name='payment',
                                 related_query_name='payment',
                                 verbose_name=_('Корзина'))

server/apps/store/views/basket.py
from django.forms import modelformset_factory
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import RedirectView
from django_jinja.views.generic import DetailView

from apps.store.utils.basket_manager import (
    get_or_create_basket, update_product_in_basket, math_basket,
    get_basket_product)
from shared.mixins import BreadcrumbMixin
from ..forms import BasketVariantProductForm
from ..models import ProductVariant, BasketProduct


class AddProductInBasketView(RedirectView):

    def setup(self, request, *args, **kwargs):
        super(AddProductInBasketView, self).setup(request=request, args=args,
                                                  kwargs=kwargs)
        self.basket = get_or_create_basket(request)
        self.product_variant = get_object_or_404(ProductVariant,
                                                 pk=kwargs['pk'])

    def get(self, request, *args, **kwargs):
        update_product_in_basket(self.basket, self.product_variant,
                                 request.GET['count'])
        math_basket(self.basket)
        return redirect(request.META.get('HTTP_REFERER'))


class BasketView(BreadcrumbMixin, DetailView):
    template_name = 'store/basket.jinja'
    basket_variant_product_form_set = (
        modelformset_factory(BasketProduct,
                             form=BasketVariantProductForm,
                             can_delete=True, max_num=0, )
    )
    form_set = None
    redirect_page = reverse_lazy('store:main')

    def get_object(self, queryset=None):
        return get_or_create_basket(self.request)

    def get_breadcrumbs(self):
        breadcrumbs = super(BasketView, self).get_breadcrumbs()
        breadcrumbs.append(self.build_breadcrumb(
            title=_('Basket')
        ))
        return breadcrumbs

    def setup(self, request, *args, **kwargs):
        super(BasketView, self).setup(request=request, args=args,
                                      kwargs=kwargs)

        basket = self.get_object()
        print(basket)
        if basket.products.count() > 0:
            qs = get_basket_product(basket)
            self.form_set = self.basket_variant_product_form_set(queryset=qs)

    def get_context_data(self, **kwargs):
        context = super(BasketView, self).get_context_data(**kwargs)
        context['form_set'] = self.form_set

        return context

    def post(self, request, *args, **kwargs):
        form_set = self.basket_variant_product_form_set(request.POST)

        if form_set.is_valid():
            for form in form_set:
                basket_product = form.save(commit=False)
                if 'DELETE' in form.changed_data:
                    basket_product.delete()
                else:
                    if form.cleaned_data:
                        if form.cleaned_data['count'] == 0:
                            basket_product.delete()
                        else:
                            basket_product.save()
            update_basket = math_basket(self.get_object())
            if update_basket.count == 0:
                return redirect(self.redirect_page)
        return self.get(request, args, kwargs)

server/markup/templates/store/basket.jinja
{% extends 'core/base.jinja' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<div class="container">
    {% if form_set %}
        {% with show_button=True %}
    {% include 'store/basket_form.jinja' %}
    {% endwith %}
    <a href="{{url('store:main') }}"> {% trans %} Продолжить покупки {% endtrans %}</a>
    <a href="{{url('store:ordering') }}"> {% trans %} Сделать заказ {% endtrans %}</a>
    {% else %}
    {% trans %}Ваша корзина пуста, самое время делать покупки {% endtrans %}
    <a href="{{url('store:main') }}">
        {% trans %} Продолжить покупки {% endtrans %}</a>
    {% endif %}
</div>
{% endblock %}

server/markup/templates/store/basket_form.jinja
<form action="" method="post">
    {{ form_set.management_form }}
    {% for form in form_set %}
    <div class="row">
        <div class="col">
            {{ form.as_table() }}
        </div>
    </div>
    {%endfor %}
    <input type='hidden' name='csrfmiddlewaretoken'
           value='{{ csrf_token }}'/>
    {% if show_button %}
    <input type="submit"
           value="{% trans %} Обновить количество {% endtrans %}">
    {% endif %}
</form>

server/markup/templates/store/info_page.jinja
{% extends 'core/base.jinja' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<div class="container">
    {{massage }}
</div>
{% endblock %}

server/markup/templates/store/liqpay.jinja
{% extends 'core/base.jinja' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<div class="container">
    <form method="POST" action="https://www.liqpay.ua/api/3/checkout"
          accept-charset="utf-8">
        <input type="hidden" name="data"
               value="{{data}}"/>
        <input type="hidden" name="signature"
               value="{{signature}}"/>
        <input type="image" src="//static.liqpay.ua/buttons/p1ru.radius.png"/>
    </form>
</div>
{% endblock %}

server/markup/templates/store/order_result.jinja
{% extends 'core/base.jinja' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<div class="container">
    <p>{% trans %} Способ доставки {% endtrans %} {{object.delivery}}</p>
    <p>{% trans %} Способ оплаты {% endtrans %} {{object.payment_method}}</p>
    <p>{% trans %} Стоимость товаров {% endtrans %}
        {{object.pay.price_products}}</p>
    <p>{% trans %} Способ доставки {% endtrans %}
        {{object.pay.price_delivery}}</p>
    <p>{% trans %} К оплате: {% endtrans %} {{object.pay.price}}</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit"
               value="{% trans %} Подтвердить заказ {% endtrans %}">
    </form>

</div>
{% endblock %}

server/markup/templates/store/ordering.jinja
{% extends 'core/base.jinja' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<div class="container">
    {% if form_set %}
    {% with show_button=False %}
    {% include 'store/basket_form.jinja' %}
    {% endwith %}
    {% endif %}
    <form method="post" id="Form"
          data-warehouses-url="{{ url('store:ajax_load_warehouses') }}"
          data-cities-url="{{ url('store:ajax_load_cities') }}">
        {% csrf_token %}
        {{ user_form.as_p() }}
        {{ordering_form.as_p()}}
        {{ warehouse_form.as_p() }}
        <button type="submit">Save</button>
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
    $("#id_city").change(function () {
      var url = $("#Form").attr("data-warehouses-url");  // get the url of the `load_cities` view
      var cityId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'city': cityId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_street").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });

    </script>

    <script>
    $("#id_search_city").change(function () {
      var url = $("#Form").attr("data-cities-url");
      var search = $(this).val();

      $.ajax({
        url: url,
        data: {
          'search': search
        },
        success: function (data) {
          $("#id_city").html(data);
        }
      });

    });







    </script>

</div>
{% endblock %}

server/markup/templates/store/product.jinja
{% extends 'core/base.jinja' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}

<div class="container">
    <div id="left" class="row col-sm-12">
        <div id="left" class="col-sm-6">
            <a href="">
                <img src="{{ product.preview.url }}"
                     width="150" height="150"
                     alt="{{ product.alt }}"
                     class="img-thumbnail">
            </a>
            <p>
                {% trans %} Оставить отзыв {% endtrans %}
            </p>
            {% include 'core/massager.jinja' %}
            <form action="" method="post">
                {% csrf_token %}
                {{ review_form.as_p() }}
                <input type="submit"
                       value="{% trans %}Оставить отзыв{% endtrans %}">
            </form>

        </div>
        <div id="right" class="col-sm-6">
            <h3>{{ product.title }}</h3>
            <p>Артикул {{current_variant.vendor_code}} </p>
            <p>Бренд {{product.brand }}</p>
            <p>
                Создана:
                {{ product.created_at.strftime('%Y-%m-%d %H:%M') }}</p>
            <p>
                Обновлено:
                {{ product.updated_at.strftime('%Y-%m-%d %H:%M') }}</p>
            {% if product.average_rating != 0 %}
            <p>Средний рейтинг: {{ product.average_rating }}</p>
            {% endif %}
            <p>Цена {{get_price(request, curse,current_variant.price)}} </p>
            {% if current_variant.price_sale != 0 %}
            <p>Цена по скидке {{ current_variant.price_sale}}</p>
            {% endif %}
            <p>Описание {{ product.description }}</p>
            <p> Цвета</p>
            {% for color, atr in color_list.items() %}
            <a href="{{atr.href}}">{{color}}</a>
            {{atr.status}}
            {% endfor %}

            <p> Размеры</p>
            {% for size, atr in size_list.items() %}
            <a href="{{atr.href}}">{{size}}</a>
            {{atr.status}}
            {% endfor %}
            <br/>
            <form action="{{url('store:add_basket', current_variant.pk) }}"
                  method="get">
                <input type='hidden' name='csrfmiddlewaretoken'
                       value='{{ csrf_token }}'/>
                {{ basket_product_form.as_p() }}
                {% for field in basket_product_form %}
                {% if field.name == 'in_basket' %}
                {% if field.value() == False %}
                <input type="submit"
                       value="{% trans %} Добавить в корзину {% endtrans %}">
                {% else %}
                <p>{% trans %} Товар уже в корзине {% endtrans %}</p>
                <input type="submit"
                       value="{% trans %} Обновить количество? {% endtrans %}">
                {% endif %}
                {% endif %}
                {% endfor %}
            </form>
            <p>{% trans %} Отзывы {% endtrans %}</p>
            {% if reviews %}
            {% for review in reviews %}
            <p>
                {{ review.rating }} * {{ review.user_name }}
                {{review.created_at|timesince}} {%trans%} назад{% endtrans %}
            </p>
            <p>
                {{ review.comment }}
            </p>
            {% endfor %}
            {% block pagination %}
            {% include 'core/pagination.jinja' %}
            {% endblock %}
            {% else %}
            {% endif %}
        </div>
    </div>

</div>
{% endblock %}

server/markup/templates/store/shop.jinja
{% extends 'core/base.jinja' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        {% for category in main_category_list %}
        <div class="col-md-3">
            <p>{{ category.name }}</p>

            <a href="{{ url('store:main_category', category.slug) }}">
                <img src="{{ category.preview.url }}"
                     width="150" height="150"
                     alt="{{ category.alt }}"
                     class="img-thumbnail">
            </a>

            <p>{% trans %} Описание: {% endtrans %}
                {{ category.description }}</p>

        </div>
        {% endfor %}
    </div>
    <div class="row g-2 gy-20">
        <div class="col-md-8 col-xs-12 main">
            {% if product_list %}
            <p>{% trans %}Диапазон цены {% endtrans %}</p>
            <p>{% trans %}От {% endtrans %} {{get_price(request, curse,
                min)}} {% trans %} до {% endtrans %}{{get_price(request, curse,
                max)}} </p>
            <p>{% trans %} Количество совпадений {% endtrans %} {{
                count}} </p>
            {% for product in product_list %}
            <div id="left" class="row col-sm-12">

                <div id="left" class="col-sm-6">
                    <a href="{{product.get_absolute_url()}}?variant={{product.variants.first().id}}">
                        <img src="{{ product.preview.url }}"
                             width="150" height="150"
                             alt="{{ product.alt }}"
                             class="img-thumbnail">
                    </a>
                </div>
                <div id="right" class="col-sm-6">
                    <a href="{{product.get_absolute_url()}}?variant={{product.variants.first().id}}">
                        <h3>{{ product.title }}</h3>
                    </a>
                    <p>
                        Создана:
                        {{ product.created_at.strftime('%Y-%m-%d %H:%M') }}</p>
                    <p>
                        Обновлено:
                        {{ product.updated_at.strftime('%Y-%m-%d %H:%M') }}</p>
                    <p>Средний рейтинг: {{ product.average_rating }}</p>
                    {% for var in product.variants.iterator() %}
                    <p> {{var }} </p>
                    {% endfor %}
                    <p>Цена {{get_price(request, curse,
                        product.variants.first().price) }}</p>

                </div>
            </div>
            {% endfor %}
            {% else %}
            <div id="left" class="row col-sm-12">
                <div id="left" class="col-sm-6">
                    {% trans %} Нет товаров по вашему запросу {% endtrans %}
                </div>
                <div id="right" class="col-sm-6">
                </div>
            </div>
            {% endif %}
        </div>

        <div class="col-md-4 col-xs-12 sidebar">
            {% if sub_category_list %}
            <p>Подкатегории</p>
            {% for category in sub_category_list %}
            <div class="col-md-3">
                <a href="{{ url('store:sub_category', category.parent.slug, category.slug) }}">
                    {{ category.name }}
                </a>
            </div>
            {% endfor %}
            {% endif %}

            <p>Блок фильтрации</p>
            <form method="get">
                {{ filter.form.as_p() }}
                <input class="btn btn-primary" value="Искать"
                       type="submit"/>
                <a class="btn btn-primary" href="{{request.path}}">
                    Сбросить фильтр</a>
            </form>
        </div>
    </div>
    <br/>
    {% block pagination %}
    {% include 'core/pagination.jinja' %}
    {% endblock %}
</div>
{% endblock %}